// Shared ETF list used by ETFSearch and Watchlist
export const ETF_LIST = [
  { ticker: "SPY",  name: "S&P 500" },
  { ticker: "QQQ",  name: "Nasdaq 100" },
  { ticker: "IWM",  name: "Russell 2000" },
  { ticker: "DIA",  name: "Dow Jones" },
  { ticker: "VOO",  name: "Vanguard S&P 500" },
  { ticker: "VTI",  name: "Vanguard Total Market" },
  { ticker: "VEA",  name: "Vanguard Developed Mkts" },
  { ticker: "VWO",  name: "Vanguard Emerging Mkts" },
  { ticker: "EFA",  name: "iShares MSCI EAFE" },
  { ticker: "EEM",  name: "iShares MSCI Emerging" },
  { ticker: "AGG",  name: "Core US Bond" },
  { ticker: "TLT",  name: "20+ Year Treasury" },
  { ticker: "IEF",  name: "7-10 Year Treasury" },
  { ticker: "SHY",  name: "1-3 Year Treasury" },
  { ticker: "LQD",  name: "Investment Grade Corp Bond" },
  { ticker: "HYG",  name: "High Yield Corp Bond" },
  { ticker: "GLD",  name: "Gold" },
  { ticker: "SLV",  name: "Silver" },
  { ticker: "USO",  name: "Oil" },
  { ticker: "UNG",  name: "Natural Gas" },
  { ticker: "XLK",  name: "Technology Sector" },
  { ticker: "XLF",  name: "Financials Sector" },
  { ticker: "XLE",  name: "Energy Sector" },
  { ticker: "XLV",  name: "Health Care Sector" },
  { ticker: "XLI",  name: "Industrials Sector" },
  { ticker: "XLC",  name: "Communication Services" },
  { ticker: "XLY",  name: "Consumer Discretionary" },
  { ticker: "XLP",  name: "Consumer Staples" },
  { ticker: "XLB",  name: "Materials Sector" },
  { ticker: "XLRE", name: "Real Estate Sector" },
  { ticker: "XLU",  name: "Utilities Sector" },
  { ticker: "VNQ",  name: "Vanguard Real Estate" },
  { ticker: "ARKK", name: "ARK Innovation" },
  { ticker: "TQQQ", name: "3x Nasdaq 100 Bull" },
  { ticker: "SQQQ", name: "3x Nasdaq 100 Bear" },
  { ticker: "SPXL", name: "3x S&P 500 Bull" },
  { ticker: "UVXY", name: "1.5x VIX Short-Term" },
  { ticker: "VXX",  name: "iPath VIX Short-Term" },
  { ticker: "IBIT", name: "iShares Bitcoin" },
  { ticker: "BITO", name: "ProShares Bitcoin Strategy" },
  { ticker: "SOXX", name: "Semiconductors" },
  { ticker: "SMH",  name: "VanEck Semiconductors" },
  { ticker: "CIBR", name: "Cybersecurity" },
  { ticker: "BOTZ", name: "Robotics & AI" },
  { ticker: "ICLN", name: "Clean Energy" },
  { ticker: "MCHI", name: "iShares MSCI China" },
  { ticker: "FXI",  name: "China Large-Cap" },
  { ticker: "EWJ",  name: "iShares MSCI Japan" },
  { ticker: "EWZ",  name: "iShares MSCI Brazil" },
  { ticker: "RSP",  name: "S&P 500 Equal Weight" },
  { ticker: "MTUM", name: "iShares MSCI Momentum" },
  { ticker: "QUAL", name: "iShares MSCI Quality" },
  { ticker: "USMV", name: "iShares Min Volatility" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity" },
  { ticker: "VIG",  name: "Vanguard Dividend Appreciation" },
  { ticker: "NOBL", name: "S&P 500 Dividend Aristocrats" },
  { ticker: "DVY",  name: "iShares Select Dividend" },
  { ticker: "QYLD", name: "Nasdaq Covered Call" },
  { ticker: "XYLD", name: "S&P 500 Covered Call" },
]
